name: prompt-engineering-for-developers

channels:
  - conda-forge
  - defaults

dependencies:
  - aiohttp
  - faiss-cpu
  - jupyterlab
  - pip
  - pip:
    - -r requirements.txt
  - python
  - tiktoken
  
