name: prompt-engineering-for-developers

channels:
  - conda-forge
  - defaults

dependencies:
  - dask
  - deepmerge
  - diffusers
  - faiss-cpu
  - gradio
  - jupyter-ai-magics
  - jupyterlab
  - langchain
  - nbgitpuller
  - openai
  - pillow
  - pip
  - pip:
    - -r requirements.txt
  - python
  - tiktoken
