name: prompt-engineering-for-developers

channels:
  - conda-forge
  - defaults

dependencies:
  - dask
  - deepmerge
  - faiss-cpu
  - jupyter-ai-magics
  - jupyterlab
  - langchain
  - nbgitpuller
  - openai
  - pip
  - pip:
    - -r requirements.txt
  - python
  - sentence-transformers
  - tiktoken
